### ISSUE TITLE
Redis SO_RCVTIMEO Invalid argument

### ISSUE THREAD

**Issue by fixmk** [TablePlus/TablePlus#1437]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    Redis Server:
```127.0.0.1:6379> INFO
# Server
redis_version:4.0.11
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:36d5e43301070694
redis_mode:standalone
os:Linux 4.9.125-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.4.0
```
   Redis CLI: 5.0.5
   OS: MacOS Mojave 10.14.4 Beta (18E220a)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 290

3. The steps to reproduce this issue:
- Create new Redis container in docker with default configuration and run it
```   
redis:
     image: redis:alpine
     restart: always
     hostname: redis
     ports:
       - "6379:6379"
 ```
- Create new connection with 127.0.0.1:6379 (which is default)
- Try to Test or Connect
- It outputs an error "setsockopt(SO_RCVTIMEO): Invalid argument"

**Comment by huyphams** [comment]
Hey, @fixmk can you check that the port was exposed successfully (By using CLI or other clients)

**Comment by devrsw** [comment]
Had this issue as well - but fixed when exposing the 6379 port:

```
redis:
  image: redis:alpine
  restart: always
  hostname: redis
  ports:
    - "6379:6379"
  expose:
    - 6379
```
