### ISSUE TITLE
Redis (SO_RCVTIMEO): Invalid argument

### ISSUE THREAD

**Issue by nessor** [TablePlus/TablePlus#2339]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

- Redis over DBngin

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

- Version 3.12.5 (364)

3. The steps to reproduce this issue:

- Start Redis in DBngin
- Setup a Redis DB connection in TablePlus with 127.0.0.1 as host and 6379 as port
- Click "Test" for testing the connection

On a MacBook Pro M1 BigSur 11.2.2

**Comment by TheMartes** [comment]
For people who are googling this, since solution for this could be a lot tricky.. this is `docker-compose` config you should use. 
```
  redis-devel:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
```
alternatively you can use also this to run it as standalone container
`docker run --name=redis-devel --publish=6379:6379 --hostname=redis --restart=on-failure --detach redis:latest`

I guess the error message could be also a lot clearer from table plus side, bcs right know it doesn't make any sense 😁
